version: '3.9'

services:
  app1:
    build: .
    container_name: fastapi_app1
    volumes:
      - ./app:/app/app
      - ./data:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  app2:
    build: .
    container_name: fastapi_app2
    volumes:
      - ./app:/app/app
      - ./data:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  app3:
    build: .
    container_name: fastapi_app3
    volumes:
      - ./app:/app/app
      - ./data:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app1
      - app2
      - app3
